config/routes.rb
Ntu::Application.routes.draw do
  resources :articles
  get '/delete/noway/article/:id' => 'articles#destroy'
  scope '/api' do
    resources :tags
    resources :enrolls
    resources :users
  end
  root :to => 'home#index'
  get '/get_enroll' => 'home#get_enroll'
  get '/youtube/:id' => 'home#getYoutube'
  get '/get_article' => 'articles#api_index'
  get '/enrolls' => 'home#show'
  get '/bulletin' => 'home#bulletin'
  get '/get_current_user' => 'application#get_current_user'
  post '/view_increase' => 'enrolls#view'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :context, :title, :image
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "admin", except: [:api_index]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @users = User.all
    @enrolls = Enroll.all
    @article = Article.new
    @title = 'NTU EPC - Bulletin'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end
  def api_index
    @articles = Article.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id])
  end
  # GET /articles/1
  # GET /articles/1.json
  # GET /articles/new
  # GET /articles/new.json

  # GET /articles/1/edit
  def edit
    @title = 'NTU EPC - Bulletin'
    @article = Article.find(params[:id])
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @articles }
    # end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to articles_url, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <img ng-src="{{image}}" width="70%" style="max-height: 500px;">
    <%= f.text_field :image, :id=>"image" , :'ng-click' => 'image()' ,:value=>"{{image}}"%>
  </div>
  <div class="field">
    <%= f.label :context %><br />
    <%= f.text_area :context %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div ng-controller='myApp'>
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

</div>

app/views/articles/index.html.erb
<link rel="stylesheet" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.min.css">
<script type="text/javascript" src='//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'></script>
<script type="text/javascript">
$(document).ready(function(){
$('#enrolls').DataTable({"scrollX": true});
$('#users').DataTable({"scrollX": true});
});
</script>
<div id="features-wrapper" ng-controller='myApp'>
  <div class="container">
    <h1>Listing Users</h1>
    <table id='users'>
      <thead>
        <th>Image</th>
        <th>Name</th>
        <th>Email</th>
        <th>Education</th>
        <th>Gender</th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag(user.image) %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.education %></td>
          <td><%= user.gender %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br />
  </div>
  <div class="container">
    <h1>Listing Enrolls</h1>
    <table id='enrolls'>
      <thead>
        <th>Image</th>
        <th>Name</th>
        <th>Email</th>
        <th>School</th>
        <th>Grade</th>
        <th>Major</th>
        <th>Cellphone</th>
        <th>VideoUrl</th>
        <th>VideoInfo</th>
        <th>Topic</th>
        <th>View</th>
        <th>User_id</th>
      </thead>
      <tbody>
        <% @enrolls.each do |enroll| %>
        <tr>
          <td><%= image_tag(enroll.image, width: '50px') %></td>
          <td><%= enroll.name %></td>
          <td><%= enroll.email %></td>
          <td><%= enroll.school %></td>
          <td><%= enroll.year %></td>
          <td><%= enroll.major %></td>
          <td><%= enroll.cellphone %></td>
          <td><%= enroll.videoUrl %></td>
          <td><%= enroll.videoInfo %></td>
          <td><%= enroll.topic %></td>
          <td><%= enroll.view %></td>
          <td><%= enroll.user_id %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br />
  </div>
  <div class="container">
    <h1>Listing articles</h1>
    <table>
      <thead class="row">
        <th class="4u">Title</th>
        <th class="6u">Context</th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
        <tr class="row">
          <td class="4u"><%= article.title %></td>
          <td class="6u"><%= article.context.html_safe %></td>
          <td class="1u"><%= link_to 'Edit', edit_article_path(article) %></td>
          <td class="1u"><%= link_to 'Destroy', '/delete/noway/article/'+article.id.to_s %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br />
    <%= render 'form' %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>